version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.10"

sphinx:
  configuration: docs/source/conf.py

# Build PDF & ePub
formats:
  - epub
  - pdf

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements-docs.txt
