name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust this to your dependencies file if needed

      - name: Run tests with pytest
        run: |
          python -m pip install pytest
          pytest  # Adjust this command if specific options or directories are needed

      - name: Extract version from release tag
        id: get_version
        run: |
          # Extract the version from the release tag (assumes tags are in the form "vX.X.X")
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=${VERSION}" >> $GITHUB_ENV

      - name: Update version in setup.py and conf.py
        run: |
          echo "Updating version to ${{ env.version }} in setup.py and conf.py"
          sed -i "s/version=.*,/version='${{ env.version }}',/" setup.py
          sed -i "s/release = .*/release = '${{ env.version }}'/" docs/source/conf.py

      - name: Build release distributions
        run: |
          python -m pip install build
          python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write

    environment:
      name: pypi

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
